# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9bcdfdbaee73e8ec5bb719ba32a297dc"
name = "Subscriptions application"
application_url = "https://subscriptions-reference-app.vercel.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "unstable"

  [[webhooks.subscriptions]]
  topics = [ "subscription_contracts/cancel" ]
  uri = "/webhooks/subscription_contracts/cancel"

  [[webhooks.subscriptions]]
  topics = [ "subscription_billing_attempts/success" ]
  uri = "/webhooks/subscription_billing_attempts/success"

  [[webhooks.subscriptions]]
  topics = [ "subscription_contracts/create" ]
  uri = "/webhooks/subscription_contracts/create"

  [[webhooks.subscriptions]]
  uri = "/webhooks/customer_redact"
  compliance_topics = [ "customers/data_request", "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/shop_redact"
  compliance_topics = [ "shop/redact" ]

  [[webhooks.subscriptions]]
  topics = [ "subscription_billing_attempts/failure" ]
  uri = "/webhooks/subscription_billing_attempts/failure"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "selling_plan_groups/create", "selling_plan_groups/update" ]
  uri = "/webhooks/selling_plan_groups/create_or_update"

  [[webhooks.subscriptions]]
  topics = [ "subscription_contracts/pause" ]
  uri = "/webhooks/subscription_contracts/pause"

  [[webhooks.subscriptions]]
  topics = [ "subscription_billing_cycles/skip" ]
  uri = "/webhooks/subscription_billing_cycles/skip"

  [[webhooks.subscriptions]]
  topics = [ "subscription_contracts/activate" ]
  uri = "/webhooks/subscription_contracts/activate"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "customer_read_orders,read_all_orders,read_customer_payment_methods,read_locales,read_locations,read_own_subscription_contracts,read_themes,write_customers,write_metaobject_definitions,write_metaobjects,write_orders,write_own_subscription_contracts,write_products,write_translations"

[auth]
redirect_urls = [
  "https://subscriptions-reference-app.vercel.app/auth/callback",
  "https://subscriptions-reference-app.vercel.app/auth/shopify/callback",
  "https://subscriptions-reference-app.vercel.app/api/auth/callback"
]

[pos]
embedded = false
